default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-submodules
      - id: no-commit-to-branch
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-added-large-files
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-xml
      - id: check-ast
      - id: debug-statements
      - id: check-builtin-literals
      - id: name-tests-test
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.82.1
    hooks:
      - id: renovate-config-validator
        args: [--strict]
  # TODO: add nectos/act --dry-run to test the workflow locally
